### ISSUE TITLE
Accept  raw URL as input

### ISSUE THREAD

**Issue by ptitzler** [ibm-cds-labs/simple-data-pipe-connector-reddit#4]
Simplify user input by asking for the raw AMA URL
https://www.reddit.com/r/IAmA/comments/43w32a/i_am_dominic_monaghan_host_of_wild_things_and/
instead of a modified version
https://www.reddit.com/r/IAmA/comments/43w32a/i_am_dominic_monaghan_host_of_wild_things_and.json

**Comment by chetnawarade** [comment]
Instead of asking users to append .json to the raw url +1 @ptitzler

**Comment by ptitzler** [comment]
The user can now enter https://www.reddit.com/r/IAmA/comments/43w32a/i_am_dominic_monaghan_host_of_wild_things_and/ or https://www.reddit.com/r/IAmA/comments/43w32a/i_am_dominic_monaghan_host_of_wild_things_and.json
